server:
  port: 8082

spring:
  profiles:
    include: secret
  application:
    name: order-service
  messages:
    encoding: UTF-8
    basename: i18n/exception
  datasource:
    url: jdbc:mariadb://localhost:3309/early_bird_order?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ${database.password}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    redis:
      host: localhost
      port: 6380

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${sqs.access-key}
      secret-key: ${sqs.secret-key}
    sqs:
      queue-name: ${sqs.queue-name}

logging:
  level:
    com.ssonzm.earlybird.orderservice: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 3000
        permittedNumberOfCallsInHalfOpenState: 3
        maxWaitDurationInHalfOpenState: 3000
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 1000
    instances:
      customCircuitBreaker:
        baseConfig: default
