server:
  port: 8080

spring:
  profiles:
    include: secret
  application:
    name: user-service
  messages:
    basename: i18n/exception
    encoding: UTF-8
  datasource:
    url: jdbc:mariadb://localhost:3307/earlybird
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ${database.password}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.ssonzm.earlybird: DEBUG