server:
  port: 8083

spring:
  profiles:
    include: secret
  application:
    name: payment-service
  cloud:
    refresh:
      extra-refreshable: com.zaxxer.hikari.HikariDataSource
  messages:
    encoding: UTF-8
    basename: i18n/exception
  datasource:
    url: jdbc:mariadb://localhost:3311/early_bird_payment?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ${database.password}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.ssonzm.paymentservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, bean, httpexchanges, busrefresh