server:
  port: 8081

spring:
  profiles:
    include: secret
  application:
    name: product-service
  cloud:
    refresh:
      extra-refreshable: com.zaxxer.hikari.HikariDataSource
  messages:
    encoding: UTF-8
    basename: i18n/exception
  datasource:
    url: jdbc:mariadb://localhost:3310/early_bird_product?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ${database.password}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: localhost
      port: 6381

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${sqs.access-key}
      secret-key: ${sqs.secret-key}
    sqs:
      queue-name: ${sqs.queue-name}

logging:
  level:
    org:
      springframework:
        transaction:
          interceptor:
            TransactionInterceptor: TRACE
        kafka:
          core:
            KafkaTemplate: TRACE
            DefaultKafkaProducerFactory: TRACE

resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 30 # 실패율 임계값(30% 이상 실패하면 Open 상태로 전환)
        slowCallRateThreshold: 50 # 느린 호출 비율 임계값 (50% 이상 느린 호출이면 Open 상태로 전환)
        slowCallDurationThreshold: 7000 # 느린 호출 지속 시간 임계값 (7초 이상 지연되면 느린 호출로 간주)
        permittedNumberOfCallsInHalfOpenState: 10 # 반 열린 상태에서 허용되는 호출 수
        maxWaitDurationInHalfOpenState: 5000 # 반 열린 상태 최대 대기 시간
        slidingWindowType: COUNT_BASED # 슬라이딩 윈도우 유형
        slidingWindowSize: 100 # 슬라이딩 윈도우 크기
        minimumNumberOfCalls: 10 # 최소 호출 수
        waitDurationInOpenState: 300000 # 열린 상태 대기 시간
        automatic-transition-from-open-to-half-open-enabled: true # 자동 열린 상태 -> 반 열린 상태 전환 활성화
        record-exceptions: # 예외 기록 목록
          - com.ssonzm.coremodule.exception.CommonBadRequestException
          - feign.FeignException
    instances:
      customCircuitBreaker:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, bean, httpexchanges, busrefresh