server:
  port: 8081

spring:
  profiles:
    include: secret
  application:
    name: product-service
  messages:
    encoding: UTF-8
    basename: i18n/exception
  datasource:
    url: jdbc:mariadb://localhost:3310/early_bird_product?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ${database.password}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    redis:
      host: localhost
      port: 6380

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.ssonzm.earlybird: DEBUG